import pytest
from hive.components.new_order_processor.organism import Neworderprocessor
from hive.components.new_order_processor.contracts import (
    CreateneworderCommand,
    OrdercreatedEvent,
    OrderrejectedEvent,
)

# This file is auto-generated by the Genesis Engine.
# Please fill in the tests to ensure the organism behaves as expected.

@pytest.fixture
def organism() -> Neworderprocessor:
    """Provides a fresh instance of the organism for each test."""
    return Neworderprocessor()

def test_organism_creation(organism: Neworderprocessor):
    """Tests that the organism can be created successfully."""
    assert organism is not None
    assert organism.genome.purpose == "Handles the initial creation and validation of a customer order."


def test_handle_creation_command_handler_success(organism: Neworderprocessor):
    """
    Tests that a valid command results in an OrdercreatedEvent.
    """
    # Arrange
    command = CreateneworderCommand(
        customer_id="cust-123",
        items=["honey-jar-1", "pollen-basket-2"],
        correlation_id="test-corr-id-1"
    )
    initial_nectar = organism.metabolism.nectar_level

    # Act
    result_event = organism.main_function(command)

    # Assert
    assert isinstance(result_event, OrdercreatedEvent)
    assert result_event.customer_id == "cust-123"
    assert result_event.items == ["honey-jar-1", "pollen-basket-2"]
    assert result_event.correlation_id == "test-corr-id-1"
    assert "order-" in result_event.order_id
    assert organism.metabolism.nectar_level == initial_nectar - 20

def test_handle_creation_command_handler_rejection(organism: Neworderprocessor):
    """
    Tests that a command with no items results in an OrderRejectedEvent.
    """
    # Arrange
    command = CreateneworderCommand(
        customer_id="cust-456",
        items=[], # No items should cause rejection
        correlation_id="test-corr-id-2"
    )
    initial_nectar = organism.metabolism.nectar_level

    # Act
    result_event = organism.main_function(command)

    # Assert
    assert isinstance(result_event, OrderrejectedEvent)
    assert result_event.customer_id == "cust-456"
    assert result_event.reason == "Order must contain at least one item."
    assert result_event.correlation_id == "test-corr-id-2"
    assert organism.metabolism.nectar_level == initial_nectar - 20