from dataclasses import dataclass
from typing import List, Any

# This file is auto-generated by the Genesis Engine.
# It defines the data contracts (Commands and Events) for the Neworderprocessor organism.

# --- Commands (Inputs) ---

@dataclass
class CreateneworderCommand:
    """Command to trigger the 'handle_creation_command' action."""
    # TODO: Define the fields required for this command.
    # Example:
    # order_id: str
    # items: List[str]
    pass


# --- Events (Outputs) ---

@dataclass
class OrdercreatedEvent:
    """Event indicating that 'OrderCreated' has occurred."""
    # TODO: Define the payload for this event.
    # Example:
    # order_id: str
    # status: str
    pass

@dataclass
class OrderrejectedEvent:
    """Event indicating that 'OrderRejected' has occurred."""
    # TODO: Define the payload for this event.
    # Example:
    # order_id: str
    # status: str
    pass
