from dataclasses import dataclass
from typing import List, Any

# This file is auto-generated by the Genesis Engine.
# It defines the data contracts (Commands and Events) for the Neworderprocessor organism.

# --- Commands (Inputs) ---

@dataclass
class CreateneworderCommand:
    """Command to trigger the 'handle_creation_command' action."""
    customer_id: str
    items: List[str]
    correlation_id: str


# --- Events (Outputs) ---

@dataclass
class OrdercreatedEvent:
    """Event indicating that 'OrderCreated' has occurred."""
    order_id: str
    customer_id: str
    items: List[str]
    correlation_id: str

@dataclass
class OrderrejectedEvent:
    """Event indicating that 'OrderRejected' has occurred."""
    customer_id: str
    reason: str
    correlation_id: str
