# Generated by The Genesis Engine: command.py.tpl
from dataclasses import dataclass

@dataclass
class {class_name}:
    """
    A command object representing the intent to perform an action.
    It is a simple Data Transfer Object (DTO).
    """
    # This would be populated with fields relevant to the command
    target_id: str
    some_value: str
    another_value: int
