# Generated by The Genesis Engine: dto.py.tpl
from dataclasses import dataclass
from typing import Any

@dataclass
class {class_name}DTO:
    """
    A Data Transfer Object representing the result of a query.
    It is a simple, read-only data structure.
    """
    # This would be populated with fields from the query result
    id: str
    data: Any
