# Generated by The Genesis Engine
# tRNA for a data payload/structure

from dataclasses import dataclass

@dataclass
class {class_name}:
    """Represents the data contract for {class_name}.
    This is the 'honey' - the precious data carried by other components.
    """
    {primary_key}: str
    # ... other fields would be defined by a richer data contract
