# Generated by The Genesis Engine: query.py.tpl
from dataclasses import dataclass

@dataclass
class {class_name}Query:
    """
    A query object representing the intent to read data.
    It is a simple Data Transfer Object (DTO).
    """
    # This would be populated with fields relevant to the query
    target_id: str
    include_details: bool = False
