# Generated by The Genesis Engine
# tRNA for a data payload/structure

from dataclasses import dataclass

@dataclass
class CreateOrderCommand:
    """Represents the data contract for CreateOrderCommand.
    This is the 'honey' - the precious data carried by other components.
    """
    user_id: str
    # ... other fields would be defined by a richer data contract
