# Generated by The Genesis Engine
# tRNA for a data payload/structure

from dataclasses import dataclass

@dataclass
class OrderData:
    """Represents the data contract for OrderData.
    This is the 'honey' - the precious data carried by other components.
    """
    order_id: str
    # ... other fields would be defined by a richer data contract
