# Generated by The Genesis Engine
# Data class for: {class_name}

from dataclasses import dataclass

@dataclass
class {class_name}:
    """Represents the data contract for {class_name}."""
    {primary_key}: str
    # ... other fields would be defined by a richer data contract
