# Generated by The Genesis Engine
# Aggregate for: OrderAggregate

from .data_models.orderdata import OrderData

class OrderAggregate:
    """Represents the OrderAggregate aggregate.
    Its state is defined by the OrderData data class.
    Primary key: order_id
    """
    def __init__(self, state: OrderData):
        self._state = state
        print(f"Aggregate {self.__class__.__name__} initialized with state.")

    def handle_command(self, command):
        print(f"Handling command in {self.__class__.__name__}...")
        # Business logic goes here.
        # This would produce and return an event.
        print(f"  - Command: {command}")
        pass
