# Generated by The Genesis Engine
# Event for: OrderPlacedEvent

from dataclasses import dataclass
from .data_models.orderplacedpayload import OrderPlacedPayload

class OrderPlacedEvent:
    """The OrderPlacedEvent Genesis Event."""
    def __init__(self, payload: OrderPlacedPayload):
        self.payload = payload
        print(f"Generated Event: {self}")

    def __repr__(self):
        return f"<{self.__class__.__name__} payload={self.payload}>"
