# Generated by The Genesis Engine
# tRNA for an Aggregate primitive

from .data_models.{data_class_lower} import {data_class}

class {class_name}:
    """Represents the {class_name} aggregate.
    Its state is defined by the {data_class} data class.
    Primary key: {primary_key}
    """
    def __init__(self, state: {data_class}):
        self._state = state
        print(f"Aggregate {{self.__class__.__name__}} initialized with state.")

    def handle_command(self, command):
        print(f"Handling command in {{self.__class__.__name__}}...")
        # Business logic goes here.
        # This would produce and return an event.
        print(f"  - Command: {{command}}")
        pass
