# Generated by The Genesis Engine
# tRNA for a Command data class

from dataclasses import dataclass

@dataclass
class {{ class_name }}Command:
    """A command to {{ command_purpose }}."""
    id: str
    # Add other command-specific fields here
