# Generated by The Genesis Engine
# tRNA for a DTO data class

from dataclasses import dataclass

@dataclass
class {{ class_name }}DTO:
    """A Data Transfer Object for returning {{ dto_purpose }}."""
    id: str
    # Add other DTO-specific fields here
