# Generated by The Genesis Engine
# tRNA for a Genesis Event primitive

from dataclasses import dataclass
from .data_models.{data_class_lower} import {data_class}

class {class_name}:
    """The {class_name} Genesis Event."""
    def __init__(self, payload: {data_class}):
        self.payload = payload
        print(f"Generated Event: {{self}}")

    def __repr__(self):
        return f"<{{self.__class__.__name__}} payload={{self.payload}}>"
