# Generated by The Genesis Engine
# tRNA for a Query data class

from dataclasses import dataclass

@dataclass
class {{ class_name }}Query:
    """A query to retrieve {{ query_purpose }}."""
    id: str
    # Add other query-specific fields here
