# Generated by The Genesis Engine
# tRNA for a Transformation primitive

class {{ class_name }}:
    """
    A stateless transformation service.
    """
    def process(self, data):
        print(f"Processing data in {{self.__class__.__name__}}...")
        # Transformation logic goes here
        transformed_data = str(data).upper()
        return transformed_data
